### ISSUE TITLE
Error when sorting collection

### ISSUE THREAD

**Issue by noorkeerat** [damiantw/laravel-scout-mysql-driver#4]
Query
`Product::search($request->get("query"))->orderBy('price', 'asc')->paginate(10);`

Screenshot
![screen](https://cloud.githubusercontent.com/assets/10139457/19676990/eb2e24b2-9ab4-11e6-9488-e3d3cecec510.png)

**Comment by damiantw** [comment]
This is actually due to a limitation in scout. The scout builder class that this driver receives an instance of does not include any support for specifying `ORDER BY` statements. 

Scout will need to be updated before this can be supported. As a work around you can use the Collection sortBy method (https://laravel.com/docs/5.3/collections#method-sortby), though it will break pagination.

**Comment by noorkeerat** [comment]
Thank you. Is there any plan to release this package without laravel scout only laravel mysql fulltext search package
